### ISSUE TITLE
Support boolean operators in findOne methods

### ISSUE THREAD

**Issue by Enoinoo** [prisma/prisma-client-js#232]
In `findMany` methods, `WhereInput` types are used, which support `AND`, `OR`, and `NOT` operators. 

However, `WhereUniqueInput` types are used in `findOne` methods, which do not support these operators. 

I'm trying to find a data model with id or another unique attribute. For now, I'm using a workaround by calling `findMany` and returning the first element in the array. But maybe these operators should be supported in `findOne`?

**Comment by divyenduz** [comment]
The upcoming [Photon.js spec](https://github.com/prisma/specs/tree/master/photonjs#basic-queries) would make this easier.

**Comment by albertoperdomo** [comment]
Hello @Enoinoo, thanks for taking the time submit your feature request.

These limitations in `findOne` exist, because we need some mechanisms to ensure there's exactly one record. This applies to all methods that rely on `WhereUniqueInput`.

- findOne
- Cursors / pagination
- updateOne
- upsert
- Connect
- Disconnect
- deleteOne

This is unlikely to change for implementation reasons to provide certain guarantees.

Workaround: Using `findMany` with `take:1` will trigger `LIMIT 1` on the query, ensuring only one result is returned, but you still need to get the first item of the array in your code. There is no performance penalty, but it doesn't feel very nice from a performance POV.

There is a separate issue for introducing a `findFirst` method, which seems to be our preferred approach to tackle this problem right now: https://github.com/prisma/prisma/issues/3676.
