### ISSUE TITLE
Stop shipping TypeScript

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#391]
As of now Photon.js uses TypeScript in its generation process.
By directly generating the right files, we can get rid of the TypeScript dependency. That will greatly improve performance and bundle size.

Related: https://github.com/prisma/photonjs/issues/388

Related: https://github.com/prisma/photonjs/issues/7

**Comment by divyenduz** [comment]
Internal note: dropping from current sprint

**Comment by janpio** [comment]
@divyenduz: Investigate a bit what this means for platforms.

**Comment by divyenduz** [comment]
This only affects AWS lambda deployments using the AWS CLI and manual packaging. All major platforms like zeit, netlify, heroku do not bundle the dev dependencies and hence, do not include typescript in their bundle.

**Comment by timsuchanek** [comment]
@divyenduz in my knowledge both heroku and netlify will ship TypeScript due to their algorithm. (Note that typescript is part of the @prisma/client bundle)
Please create a reproduction with each to be sure.

**Comment by divyenduz** [comment]
Heroku, netlify, zeit, serverless framework all platforms are able to remove typescript and Prisma CLI dependencies from `node_modules` root folder but the dependency from the client bundle itself (which lives in generator-build) stays because it is a part of the production package. Which is expected. 

E2E tests can serve as the reproductions (with adjustment of running `ls` on the `node_modules` at runtime): https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms

This means that AWS CLI is the only tool which doesn't make the bundle optimized for its size. 

However, since Prisma client is really large in size, it is easy to hit these limits in any platform. Which is why I recommend taking this one up before the release. 

I was trying to deploy a Prisma project with a Lambda layer (ffmpeg, 40MB) and I hit this limit. I assume for any large projects the limit will be hit. I could get around it by thinning my layer and pre, post deploy hooks like this: 

![image](https://user-images.githubusercontent.com/746482/73380087-b6bb3700-42c3-11ea-9a19-c17fa72c76f9.png)

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
