### ISSUE TITLE
Remove compatibility plural api

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-client-js#479]
In order to ease the transition, Prisma Client right now ships with a note with the old plural api, that it's deprecated.
We should by now remove the note, as it gets in the way with the autocompletion.

**Comment by deadcoder0904** [comment]
Any reason why this is removed? It reads weirdly

```js
// This reads weird
🤮  const blogs = await prisma.blog.findMany()

// This reads greatly
😍  const blogs = await prisma.blogs.findMany()
```

**Comment by janpio** [comment]
You refer to the old "pluralized API", not the "compatibility plural api" we had for a few versions that @timsuchanek mentioned above.

About the pluralized API:
The problem is if people already have pluralized table names like `posts` it created something like `postes` - which is _really_ awkward to use and non intuitive. Same problem in other, non English languages. Also if the table names for example use both way mixed at the same time. So for now we removed the feature. If you want to, you can use `@map` in your `schema.prisma` to rename the model (`blog` => `blogs`) which will also be reflects in Prisma Client. 

We will think about how we can improve this experience in the future - we agree with your initial statement, but have to find a better way to offer that.
