### ISSUE TITLE
Null vs undefined for optional values

### ISSUE THREAD

**Issue by krzkaczor** [prisma/prisma-client-js#572]
What's the reasoning for using `null` for optional values in generated typings? 

I feel like lots of folks prefer to use only one type to determine the absence of a value and usually, they settle on `undefined`. 

Is it possible to customize this during generation?

**Comment by schickling** [comment]
Thanks a lot for raising this issue @krzkaczor! Would you mind sharing some of your application code where you're interacting with the Prisma Client and where you'd prefer to use `undefined` instead of `null`?

**Comment by krzkaczor** [comment]
@schickling:

Building on top of https://github.com/prisma/prisma-examples/blob/prisma2/typescript/rest-express/src/index.ts

```
const users = await prisma.user.findOne({ where: { id: 1} })
```

`findOne` return type is `user | null`. Whereas I would prefer it to be `user | undefined`.

**Comment by Tajnymag** [comment]
I'm also in for such change in the api. It makes a lot of sense when working with optional attributes, which can be undefined but not null.

**Comment by benatkin** [comment]
I think undefined is a better match.

<img width="513" alt="Screen Shot 2020-09-14 at 23 10 54" src="https://user-images.githubusercontent.com/4126/93161013-a6838b00-f6df-11ea-8a9f-a43366ed778e.png">

![null-undefined](https://user-images.githubusercontent.com/4126/93160499-71c30400-f6de-11ea-8c28-c2c6cdb2e923.jpg)

**Comment by benatkin** [comment]
A well-known js dev weighs in: https://news.ycombinator.com/item?id=24956156

**Comment by matthewmueller** [comment]
Thanks for the question! In the Prisma Client there's a specific difference between `null` and `undefined`.

**`null` is a specific value that's persisted in an SQL database as `NULL`**. If I run:

```ts
prisma.user.create({ 
  data: {
    id: 10,
    customer: null
  }
}
```

The row in an SQL database looks like this:

|id|customer|
|:-|:-|
|10|NULL|

**`undefined` is the absence of any value**. That looks like this:

```ts
prisma.user.create({ 
  data: {
    id: 10,
    customer: undefined
  }
}
```

Conceptually that's the same as

```ts
prisma.user.create({ 
  data: {
    id: 10
  }
}
```

This leaves the prisma engine to decide the value falling back on the `@default` value.

This conceptual difference doesn't show up in many Javascript libraries, which is why Sindre opted to consolidate the concept. For us, the different matters. Hope this helps!
