### ISSUE TITLE
.deleteMany() causes panic, .delete() fails silently, .raw() delete works

### ISSUE THREAD

**Issue by Linktheoriginal** [prisma/prisma-client-js#600]
Since cascade deletes are not yet supported, we have added some handling to delete a set of related tables in order.

When deleting one of the tables (Person, below), a deleteMany causes a Panic, and a deleteOne fails silently (succeeds without deleting the row).  A raw delete query works.

We believe this likely has something to do with the relation handling, but the error seems to be on the Person-User relationship.  The actual schema has additional relationships, but the listed relationships seem to be causing the problem.

The concerning part to us was the silent failure on the delete - we expected this to error if there was an issue.

```prisma
model Person {
  id        Int         @default(autoincrement()) @id
  student   Student?
  parent    Parent? 
  user      User
}
model Parent {
  id               Int            @default(autoincrement()) @id
  person           Person
  students          Student[]
}
model Student {
  id            Int            @default(autoincrement()) @id
  parent        Parent
  person        Person
}
model User {
  id                       Int                        @default(autoincrement()) @id
  person                   Person?
}
```

We have a replication example that we will send directly.

**Comment by dpetrick** [comment]
Before diving deeper into this, I suggest an update to the latest beta and with it the overhauled relation definitions. This might already be resolved.

**Comment by divyenduz** [comment]
I could find a reproduction with the latest alpha where both `delete` and `deleteMany` fail silently

https://github.com/divyendu-test/prisma-client-js-600

**Comment by pantharshit00** [comment]
I can confirm the reproduction posted by @divyenduz

**Comment by dpetrick** [comment]
I looked into the issue and I don't quite understand what the actual problem is. In both cases I get `"The change you are trying to make would violate the required relation 'PersonToStudent' between the `Person` and `Student` models."`, which is exactly how it's supposed to be.

You have required relations to the `Person` model, and because there are records existing that point to the record you're trying to delete, it will fail.

Of course the raw API works, but you're left with invalid data because you bypassed the checks Prisma does to guarantee data integrity.

This is a shortcoming on our end in a sense that we need cascade support, but the behavior seen here in the issue is intended. IF you want to implement cascades yourself you need to start deleting from the non-required end upwards, not the other way around.

**Comment by Linktheoriginal** [comment]
@dpetrick You're correct about the deletion order.  The main issue was around error handling - the panic and silent failures.  If you are now getting relationship constraint violation errors thrown, that would be the fix.

**Comment by dpetrick** [comment]
Thanks for the feedback, appreciate the report.
