### ISSUE TITLE
Invalid `include` query incorrectly accepted by type system

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#607]
Schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model api_keys {
  allowed_ips   String[]
  created_at    DateTime
  created_by_id Int?
  hidden        Boolean  @default(false)
  id            Int      @default(autoincrement()) @id
  key           String
  updated_at    DateTime
  user_id       Int?     @unique

  @@index([key], name: "index_api_keys_on_key")
}
```

The following query is allowed by TypeScript but shouldn't be:

```ts
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

prisma.api_keys.findMany({ first: 1, include: { user: true } }).then(x => {
  console.log(x)
  prisma.disconnect()
})
```

![image](https://user-images.githubusercontent.com/1567498/77852385-a7326e80-71de-11ea-9211-19e1b0aa7fbb.png)

Note: I ran into this error after I've changed my Prisma schema. Initially I actually **had** a relation called `user` based on which I've written the Prisma Client query.

**Comment by janpio** [comment]
> Note: I ran into this error after I've changed my Prisma schema. Initially I actually **had** a relation called `user` based on which I've written the Prisma Client query.

Can you reproduce this in a new project with `prisma2 init` that did not have an older Client where this used to be a valid type/query? (I also have this feeling that the types sometimes are not refreshed properly, but could never really reproduce or prove it yet.)

**Comment by pantharshit00** [comment]
I think I can confirm this. This is not a particular case with "user" field you removed but if you add any non-existing field to include, typescript doesn't validate it but the resulting type is also doesn't have the information:
![image](https://user-images.githubusercontent.com/22195362/78410793-12d76a00-762b-11ea-8b94-9962428b1c4d.png)
Runtime validates it though:
![image](https://user-images.githubusercontent.com/22195362/78410830-37cbdd00-762b-11ea-86ed-3e94939b2914.png)


Select is properly typed though:
![image](https://user-images.githubusercontent.com/22195362/78410849-474b2600-762b-11ea-8498-69b05766d66e.png)

Select is validated correctly though

**Comment by timsuchanek** [comment]
This happens, because we generate an empty type, which allows excess properties ["by design"](https://github.com/microsoft/TypeScript/issues/14606), which I just learned about.

The following code compiles, even though you would not want it to compile in this case:

https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200328#code/C4TwDgpgBAsiCCAnA5lAvFA3gWAFBSggFsxQAuKAURNDwF889RIqaR0sHc8ATCAYwA2AQ0TQAZgFcAdv2ABLAPbSo46QAphFOEmQBKCgGdgiedOSNca9TnyE2FWwQLjFiiickQ8BLnT1AA

The only clean way to fix this, that I can see right now, is not even including `include` in the generated type, as an empty include doesn't do anything anyway.
