### ISSUE TITLE
Make batching and caching behaviour explicit and configurable

### ISSUE THREAD

**Issue by MattGson** [prisma/prisma-client-js#645]
## Problem
Referencing [https://github.com/prisma/prisma-client-js/issues/153#issuecomment-610861727](url)

Prisma seems like a great option as a typesafe query builder. I am considering replacing plain SQL with it going forward in a large project.

One of the things that is important for me about Prisma is that it is not an ORM and it doesn't do too much. I understand that some form of dataloader has been added recently (although I cannot find any explicit documentation of this other than the referenced issue).

In GraphQL APIs, dataloader is often a fundamental component. If I am using Prisma, I don't want to be coupled to its loading behaviour and at the very least I need to know exactly what it will and won't do. 

## Solution
Ideally I would be able to disable any such behaviour so that I can use Prisma as a drop in replacement for SQL or another query builder and use existing dataloader infrastructure.

**Comment by thebiglabasky** [comment]
Thanks @MattGson 
The data loader will be applied to whatever call you make using Prisma, meaning that you'll stay in control of what Prisma does based on how you'll use the API.
While I understand the aspiration to control settings, this is not something we plan to do in the future, since the data loader is a key part in considering how the engine runs queries.

I will close this issue, but feel free to re-open it once you face concrete use cases to share with us which make it compelling.
Thank you!
