### ISSUE TITLE
Scalar lists allows `null` to be passed in the set operation and doing that operation crashes with null value

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-client-js#780]
Ref: https://github.com/prisma/prisma/issues/847#issuecomment-658907011
## Bug description
Right now set operation for scalar lists allow `null` to be passed. 
```ts
export type UserCreatetestInput = {
  set?: Enumerable<string> | null
}
```

This should not be the case in the first place as lists in the schema are not nullable. Also, when I run following which passes null to set, it crashes:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient({
    log: ["query"],
  });

  const test = await client.user.create({
    data: {
      test: {
        set: null,
      },
      email: "test",
    },
  });
  console.log(test);
  client.disconnect();
}

main();
```

![image](https://user-images.githubusercontent.com/22195362/87575746-fa78f000-c6ed-11ea-86f1-17cf1420e91d.png)

Since, no query was sent to the engine, I would assume this is problem in our ts code which validates the query.

## How to reproduce

1. Use the following schema and create a database using prisma migrate. Also, generate the client:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
  posts   Post[]
  test    String[]
  profile Profile?
}
```

2. Run the following script:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient({
    log: ["query"],
  });

  const test = await client.user.create({
    data: {
      test: {
        set: null,
      },
      email: "test",
    },
  });
  console.log(test);
  client.disconnect();
}

main();
```

## Expected behavior

`set` should not be nullable in the first place. Prisma client should also not crash if the typing allow a query

## Environment & setup

- OS: MacOS 10.15.5
- Database: Postgres 11.8
- Prisma version:
```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.3.0-dev.31
Current platform     : darwin
Query Engine         : query-engine a1ea05fcba2ecf3d741a559a8394a61a0958b662 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli a1ea05fcba2ecf3d741a559a8394a61a0958b662 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core a1ea05fcba2ecf3d741a559a8394a61a0958b662 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt a1ea05fcba2ecf3d741a559a8394a61a0958b662 (at node_modules/@prisma/cli/prisma-fmt-darwin)

```

- Node.js version: 12.18.2

**Comment by Sytten** [comment]
Also I want to add that in the database the column is marked as nullable (aka not marked as `NOT NULL`). This should also be changed.

**Comment by do4gr** [comment]
In Postgres complete arrays can be specified as Nullable or Not Null. In addition on older Postgres versions (<=8) the array elements themselves had to be non-null. Below is an example for a complete array defined as not null. 
<img width="621" alt="Screen Shot 2020-07-27 at 19 14 47" src="https://user-images.githubusercontent.com/16278407/88688669-e5db2580-d0f9-11ea-9a6e-36731f463bd7.png">

MongoDB also allows arrays and their elements to be null. 

Since in Prisma 1 Lists always were non-nullable and could only contain non-null elements this is what is currently implemented in Prisma 2. There is no concept of nullability for lists implemented at the moment. Prisma Schema Language (PSL) and our engines define a field as either Optional, Required or a List. In order to handle the distinction that Postgres allows we need to adapt the PSL. 

@matthewmueller dug up an old RFC where we had this syntax: ` photos   Photo?[]?` with the first ? signifying nullability within the array and the second nullability of the whole array. 

We need to decide whether to proceed with this syntax. Then this issue would be a bug fix to the behavior of non-nullable lists and the addition of the other array syntax would be a new feature that allows nullable lists.

**Comment by janpio** [comment]
@matthewmueller will create a new issue for the second aspect.
