### ISSUE TITLE
Enable creation of record if not already present - `findOrCreate`

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#85]
### Problem

Whenever making use of database-stored configuration data, it is often wanted to check whether such data is available, and creating it if it’s not.
Doing that with the current client requires to add code which performs the check and creates the record if it’s not present.
Having a more concise way of performing these tasks would improve the overall developer experience.

### Solution

Implement a `findOrCreate` function taking an object as input that performs the following:

* looks for the input object using its primary key,
* if not found, it goes ahead and creates it.

**Comment by schickling** [comment]
This is currently being specced out here: https://github.com/prisma/specs/pull/5
Once the spec is ready, this feature will be ready for implementation. 👌

**Comment by thebiglabasky** [comment]
Hi, since `upsert` allows to do exactly what a `findOrCreate` function would do, I will close this issue.
I've added an issue to update our docs in order to explain how this can be done here: https://github.com/prisma/docs/issues/640

In a nutshell, you can call `upsert` with `update: {}` which will behave the same.

We currently follow a design principle going against creating multiple signatures or ways to do the same thing in the API, which means we're currently not open to add `findOrCreate` as a shortcut for this `upsert` signature.

I will thus close this issue.
