### ISSUE TITLE
Adjust default generation path to `@prisma/photon`

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-client-js#88]
Currently the default output path for the generated Photon library is `@generated/photon`. While this is working well from a technical perspective, we've received the feedback that this might be potentially problematic as we don't own the `@generated` NPM organization. 

A safer alternative would be `@prisma/generated/photon` or `@prisma/photon`.

More ideas welcome! 💡

**Comment by auderer** [comment]
I like `@prisma/generated/photon` because it keeps the "generated" keyword. It makes perfect sense to find files generated by prisma in `@prisma/generated`.

**Comment by timsuchanek** [comment]
Pushed this to `preview4` as we need more internal discussions about the consequences first.

**Comment by ralvs** [comment]
Another problem I have just found, running `npm update` removes the `@generated/photon` directory

**Comment by cloverich** [comment]
Generating this output into a node_modules folder _other_ than the prisma2 folder has the additional issue of getting wiped by `prune`, a common practice in many CI systems. The alternatives as I see them now are:

- Generate into the prisma2 folder, and declare it as a `dependency` (rather than a `devDependency`), so `prune` does not wipe it
- Generate into a source directory and add an (application specific) build step that copies the source (note since it includes a _binary_, it must be generated on the build system and may not be auto-copied by your compiler)

I love the dev experience of generating into node_modules and things just working. But it was very confusing and a bit frustrating getting it all working in CI, until I realized how it works (where I recalled I"ve done this before, with Electron and native dependencies there). My _personal_ preference would be to just generate it into a source directory and providing clear guidance and documentation on how to setup a build step for CI. Much less elegant of course, but also more transparent and educational.

**Comment by divyenduz** [comment]
@schickling any updates?

**Comment by schickling** [comment]
Based on the current feedback gathered in the preview process, generating Photon.js (and other Node libraries) - so far - seems to be a positively received design decision as we've been able to smoothen most related rough edges. Some users still prefer to check in Photon.js into version control, so generating the library into a directory as part of the application by specifying the `output` generator property.

In regards to the naming convention. We've decided to change the default generation path from `@generated/photon` to `@prisma/photon`.

**Comment by timsuchanek** [comment]
This is related to the SDK, which we first want to figure out more.
Once we have a better plan with the SDK, we'll revisit this topic.

**Comment by jasonkuhrt** [comment]
This issue came to [my attention today](https://prisma-company.slack.com/archives/C8AKVD5HU/p1568212144028800?thread_ts=1568208945.021900&channel=C8AKVD5HU&message_ts=1568212144.028800). I came to the same conclusion as @cloverich before fwiw.

**Comment by jasonkuhrt** [comment]
To @cloverich's point https://github.com/prisma/photonjs/issues/88#issuecomment-522047264, a thought, imagine:

First, see that prisma-generators could split themselves in two parts:

1. facade <-- what apps import directly `import ... from ...`
2. engine <-- what `$ prisma generate` actually runs

Then, idea:

1. apps install prisma-generators as deps, e.g.:

```bash
yarn add @prisma/nexus-prisma
yarn add @typegraphql/prisma
yarn add @prisma/photon
```

2. apps import prisma-generators as usual (the facade)

```ts
import Photon from "@prisma/photon"
```

3. In turn, prisma-generators (the facade), _internally_, import the _generated part_

```ts
// photon or typegraphql or nexus-prisma or ....
// INTERNALLY, end-user never thinks about this
import generated from '@prisma/generated/photon'
...
```

4. If users attempts to user a prisma-generator before `$ prisma generate` has been run, then the the prisma-generator facade could throw a really nice and clear error for the user, e.g.:

```
Whoops, It looks like you forgot to run $ prisma generate ...
```

5. All of the mechanics here could be wrapped inside a Prisma SDK, so that generators are easier to build, follow a consistent pattern, and provide a consistent DX

**Comment by jasonkuhrt** [comment]
I have formalized [my above comment](https://github.com/prisma/photonjs/issues/88#issuecomment-530452348) that addresses @cloverich's point https://github.com/prisma/photonjs/issues/88#issuecomment-522047264 as a new issue in https://github.com/prisma/specs/issues/152. We can achieve clean package integration without pruning issues.

The proposal could effectively resolve this issue. Depending on how it plays after further discussion.

**Comment by timsuchanek** [comment]
This is released for a while already. Thanks everyone for the feedback!
